# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  plugins:
    - custom_lint
  exclude:
    - lib/**/*.g.dart
    - lib/l10n/*.dart
    - lib/gen/*.dart
linter:
  rules:
    # import
    prefer_relative_imports: true
    always_use_package_imports: false
    sort_pub_dependencies: false

    use_setters_to_change_properties: false
    prefer_foreach: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
