name: hackathon_flutter_202309
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Architecture
  flutter_riverpod: ^2.4.0

  # immutable
  equatable: ^2.0.5
  json_annotation: ^4.8.1

  # Supabse
  supabase_flutter: ^1.10.16

  # Device API
  package_info_plus: ^4.1.0
  shared_preferences: ^2.2.1
  path_provider: ^2.1.1

  # UI
  cupertino_icons: ^1.0.2
  extended_nested_scroll_view: ^6.1.1
  extended_image: ^8.0.2
  pull_to_refresh_flutter3: ^2.0.1
  adaptive_dialog: ^1.9.0+2
  flutter_svg: ^2.0.7

  # Extend dart
  intl: ^0.18.1
  pub_semver: ^2.1.4

  # Validator
  form_validator: ^2.1.1

  # Logger
  logger: ^2.0.2

  # タイムゾーン
  timezone: ^0.9.2
  flutter_native_timezone: ^2.0.0

  # Local DB
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 静的解析
  flutter_lints: ^2.0.0
  pedantic_mono: ^1.24.0+1
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2

  # build_runner
  build_runner: ^2.4.6

  # json_serializable
  json_serializable: ^6.7.0

  # flutter_gen
  flutter_gen_runner: ^5.3.1

  # Isar
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  # assets:
    # - assets/images/png
    # - assets/images/svg

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/color/colors.xml
